UP = input()
UP = UP.split(" ")
DOWN = input() 
DOWN = DOWN.split(" ")
LEFT = input() 
LEFT = LEFT.split(" ")
RIGHT = input()
RIGHT = RIGHT.split(" ")
a =int(UP[1]) - int(DOWN[1])
b =int(LEFT[1]) - int(RIGHT[1])
print(a)
print(b)
print(int((a**2 + b**2)**0.5))
